//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.19 at 04:27:38 PM EDT 
//


package personal.xml.jaxb.bindingframework.binding.elementclass;

import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;

public class Complex
    extends JAXBElement<AComplexType>
{

    protected final static QName NAME = new QName("", "complex");

    public Complex(AComplexType value) {
        super(NAME, ((Class) AComplexType.class), null, value);
    }

    public Complex() {
        super(NAME, ((Class) AComplexType.class), null, null);
    }

}
