//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.19 at 02:17:57 PM EDT 
//


package personal.xml.jaxb.bindingframework.binding.elementclass;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the personal.xml.jaxb.bindingframework.binding.elementclass package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Complex_QNAME = new QName("", "complex");
    private final static QName _AComplexTypeASimpleElement_QNAME = new QName("", "ASimpleElement");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: personal.xml.jaxb.bindingframework.binding.elementclass
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AComplexType }
     * 
     */
    public AComplexType createAComplexType() {
        return new AComplexType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AComplexType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "complex")
    public JAXBElement<AComplexType> createComplex(AComplexType value) {
        return new JAXBElement<AComplexType>(_Complex_QNAME, AComplexType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ASimpleElement", scope = AComplexType.class)
    public JAXBElement<Integer> createAComplexTypeASimpleElement(Integer value) {
        return new JAXBElement<Integer>(_AComplexTypeASimpleElement_QNAME, Integer.class, AComplexType.class, value);
    }

}
